### ISSUE TITLE
Use `tags` instead of `branches` for cargo dependencies.

### ISSUE THREAD

**Issue by ozgunozerk** [OpenZeppelin/polkadot-runtime-template#111]
### Problem

today, after upgrading to 1.6.0, I ran `cargo clean` and `cargo check`, and I got this error: 
```
error[E0046]: not all trait items implemented, missing: `RuntimeTask`
     --> /Users/ozgunozerk/Developer/polkadot-runtime-template/runtime/src/lib.rs:277:1
      |
  277 | impl frame_system::Config for Runtime {
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `RuntimeTask` in implementation
      |
      = help: implement the missing item: `type RuntimeTask = /* Type */;`
```

I checked the sourcecode for v1.6.0 on github, and indeed this field was missing on our implementation. But, CI had passed when we merged the upgrade to v1.6.0.

After re-running `cargo check` a couple more times, the issue got fixed on its own. Which is very weird behavior. I figured out that the reason is due to branch `v1.6.0` on GitHub and the `v1.6.0` branch we checked out in our `cargo.lock` has different commits.

### Solution
Even mentioning a branch may not be sufficient as I wasted half an hour on figuring out what was the issue. I suggest we use tags instead of branches in our `cargo.toml` files.
